# Generated by Django 3.0.5 on 2020-04-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', max_length=255, upload_to='images', verbose_name='Profile Picture'),
        ),
    ]
