# Generated by Django 3.0.5 on 2020-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_upload_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='video',
            field=models.FileField(default='', upload_to='videos'),
            preserve_default=False,
        ),
    ]
