# Generated by Django 3.0.5 on 2020-04-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20200417_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
