# Generated by Django 3.0.5 on 2020-04-17 15:48

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20200417_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='video',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
