# Generated by Django 3.0.5 on 2020-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20200417_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='s3_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
