# Generated by Django 3.0.5 on 2020-04-18 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0012_auto_20200418_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='upload',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
