# Generated by Django 3.0.5 on 2020-04-18 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0013_auto_20200418_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='video_dislikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
