# Generated by Django 3.0.5 on 2020-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_upload_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
