# Generated by Django 3.0.5 on 2020-04-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0015_upload_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='content',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polls', models.ManyToManyField(blank=True, related_name='video_polls', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_name', to='video.Upload')),
            ],
        ),
    ]
