# Generated by Django 3.0.5 on 2020-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_auto_20200420_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_group',
            field=models.CharField(default='', max_length=200),
        ),
    ]
