# Generated by Django 3.0.5 on 2020-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_poll_poll_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_group',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
