# Generated by Django 3.0.5 on 2020-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_auto_20200420_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='video',
        ),
        migrations.AddField(
            model_name='poll',
            name='option',
            field=models.CharField(default='', max_length=400),
        ),
    ]
